/// Name lookup tables for SCSI constants: sense keys, ASC/ASCQ codes,
/// VPD pages, mode pages, element types, space codes, log pages, and more.

pub fn sense_key_name(key: u8) -> &'static str {
    match key {
        0x0 => "NO SENSE",
        0x1 => "RECOVERED ERROR",
        0x2 => "NOT READY",
        0x3 => "MEDIUM ERROR",
        0x4 => "HARDWARE ERROR",
        0x5 => "ILLEGAL REQUEST",
        0x6 => "UNIT ATTENTION",
        0x7 => "DATA PROTECT",
        0x8 => "BLANK CHECK",
        0x9 => "VENDOR SPECIFIC",
        0xA => "COPY ABORTED",
        0xB => "ABORTED COMMAND",
        0xC => "EQUAL (obsolete)",
        0xD => "VOLUME OVERFLOW",
        0xE => "MISCOMPARE",
        0xF => "COMPLETED",
        _ => "UNKNOWN",
    }
}

/// Exhaustive ASC/ASCQ description lookup from SPC/SSC/SMC specs.
pub fn asc_description(asc: u8, ascq: u8) -> &'static str {
    match (asc, ascq) {
        (0x00, 0x00) => "No additional sense information",
        (0x00, 0x01) => "Filemark detected",
        (0x00, 0x02) => "End-of-partition/medium detected",
        (0x00, 0x03) => "Setmark detected",
        (0x00, 0x04) => "Beginning-of-partition/medium detected",
        (0x00, 0x05) => "End-of-data detected",
        (0x00, 0x06) => "I/O process terminated",
        (0x00, 0x11) => "Audio play operation in progress",
        (0x00, 0x12) => "Audio play operation paused",
        (0x00, 0x13) => "Audio play operation successfully completed",
        (0x00, 0x14) => "Audio play operation stopped due to error",
        (0x00, 0x15) => "No current audio status to return",
        (0x00, 0x16) => "Operation in progress",
        (0x00, 0x17) => "Cleaning requested",
        (0x00, 0x1D) => "ATA pass through information available",
        (0x01, 0x00) => "No index/sector signal",
        (0x02, 0x00) => "No seek complete",
        (0x03, 0x00) => "Peripheral device write fault",
        (0x03, 0x01) => "No write current",
        (0x03, 0x02) => "Excessive write errors",
        (0x04, 0x00) => "Logical unit not ready, cause not reportable",
        (0x04, 0x01) => "Logical unit is in process of becoming ready",
        (0x04, 0x02) => "Logical unit not ready, initializing command required",
        (0x04, 0x03) => "Logical unit not ready, manual intervention required",
        (0x04, 0x04) => "Logical unit not ready, format in progress",
        (0x04, 0x07) => "Logical unit not ready, operation in progress",
        (0x04, 0x08) => "Logical unit not ready, long write in progress",
        (0x04, 0x09) => "Logical unit not ready, self-test in progress",
        (0x04, 0x0A) => "Logical unit not accessible, asymmetric access state transition",
        (0x04, 0x0B) => "Logical unit not accessible, target port in standby state",
        (0x04, 0x0C) => "Logical unit not accessible, target port in unavailable state",
        (0x04, 0x12) => "Logical unit not ready, offline",
        (0x04, 0x13) => "Logical unit not ready, SA creation in progress",
        (0x05, 0x00) => "Logical unit does not respond to selection",
        (0x06, 0x00) => "No reference position found",
        (0x07, 0x00) => "Multiple peripheral devices selected",
        (0x08, 0x00) => "Logical unit communication failure",
        (0x08, 0x01) => "Logical unit communication time-out",
        (0x08, 0x02) => "Logical unit communication parity error",
        (0x08, 0x03) => "Logical unit communication CRC error (Ultra-DMA/32)",
        (0x09, 0x00) => "Track following error",
        (0x09, 0x04) => "Head select fault",
        (0x0A, 0x00) => "Error log overflow",
        (0x0B, 0x00) => "Warning",
        (0x0B, 0x01) => "Warning - specified temperature exceeded",
        (0x0B, 0x02) => "Warning - enclosure degraded",
        (0x0B, 0x03) => "Warning - background self-test failed",
        (0x0B, 0x04) => "Warning - background pre-scan detected medium error",
        (0x0B, 0x05) => "Warning - background medium scan detected medium error",
        (0x0C, 0x00) => "Write error",
        (0x0C, 0x02) => "Write error - auto reallocation failed",
        (0x0C, 0x03) => "Write error - recommend reassignment",
        (0x0C, 0x07) => "Write error - recovery needed",
        (0x0C, 0x08) => "Write error - recovery failed",
        (0x0C, 0x09) => "Write error - loss of streaming",
        (0x0C, 0x0A) => "Write error - padding blocks added",
        (0x0D, 0x00) => "Error detected by third party temporary initiator",
        (0x0D, 0x01) => "Third party device failure",
        (0x0D, 0x02) => "Copy target device not reachable",
        (0x0D, 0x03) => "Incorrect copy target device type",
        (0x0D, 0x04) => "Copy target device data underrun",
        (0x0D, 0x05) => "Copy target device data overrun",
        (0x0E, 0x00) => "Invalid information unit",
        (0x0E, 0x01) => "Information unit too short",
        (0x0E, 0x02) => "Information unit too long",
        (0x10, 0x00) => "ID CRC or ECC error",
        (0x11, 0x00) => "Unrecovered read error",
        (0x11, 0x01) => "Read retries exhausted",
        (0x11, 0x02) => "Error too long to correct",
        (0x11, 0x04) => "Unrecovered read error - auto reallocate failed",
        (0x11, 0x0A) => "Miscorrected error",
        (0x11, 0x0B) => "Unrecovered read error - recommend reassignment",
        (0x11, 0x0C) => "Unrecovered read error - recommend rewrite the data",
        (0x11, 0x0D) => "De-compression CRC error",
        (0x11, 0x0E) => "Cannot decompress using declared algorithm",
        (0x11, 0x11) => "Read error - loss of streaming",
        (0x12, 0x00) => "Address mark not found for ID field",
        (0x13, 0x00) => "Address mark not found for data field",
        (0x14, 0x00) => "Recorded entity not found",
        (0x14, 0x01) => "Record not found",
        (0x14, 0x03) => "End-of-data not found",
        (0x14, 0x04) => "Block sequence error",
        (0x14, 0x05) => "Record not found - recommend reassignment",
        (0x15, 0x00) => "Random positioning error",
        (0x15, 0x01) => "Mechanical positioning error",
        (0x15, 0x02) => "Positioning error detected by read of medium",
        (0x16, 0x00) => "Data synchronization mark error",
        (0x16, 0x01) => "Data sync error - data rewritten",
        (0x16, 0x02) => "Data sync error - recommend rewrite",
        (0x16, 0x03) => "Data sync error - data auto-reallocated",
        (0x16, 0x04) => "Data sync error - recommend reassignment",
        (0x17, 0x00) => "Recovered data with no error correction applied",
        (0x17, 0x01) => "Recovered data with retries",
        (0x17, 0x02) => "Recovered data with positive head offset",
        (0x17, 0x03) => "Recovered data with negative head offset",
        (0x17, 0x05) => "Recovered data using previous sector ID",
        (0x18, 0x00) => "Recovered data with error correction applied",
        (0x18, 0x01) => "Recovered data with error corr. & retries applied",
        (0x18, 0x02) => "Recovered data - data auto-reallocated",
        (0x19, 0x00) => "Defect list error",
        (0x19, 0x01) => "Defect list not available",
        (0x19, 0x02) => "Defect list error in primary list",
        (0x19, 0x03) => "Defect list error in grown list",
        (0x1A, 0x00) => "Parameter list length error",
        (0x1B, 0x00) => "Synchronous data transfer error",
        (0x1C, 0x00) => "Defect list not found",
        (0x1C, 0x01) => "Primary defect list not found",
        (0x1C, 0x02) => "Grown defect list not found",
        (0x1D, 0x00) => "Miscompare during verify operation",
        (0x1E, 0x00) => "Recovered ID with ECC correction",
        (0x20, 0x00) => "Invalid command operation code",
        (0x21, 0x00) => "Logical block address out of range",
        (0x21, 0x01) => "Invalid element address",
        (0x22, 0x00) => "Illegal function (use 20 00, 24 00, or 26 00)",
        (0x24, 0x00) => "Invalid field in CDB",
        (0x25, 0x00) => "Logical unit not supported",
        (0x26, 0x00) => "Invalid field in parameter list",
        (0x26, 0x01) => "Parameter not supported",
        (0x26, 0x02) => "Parameter value invalid",
        (0x26, 0x03) => "Threshold parameters not supported",
        (0x26, 0x04) => "Invalid release of persistent reservation",
        (0x27, 0x00) => "Write protected",
        (0x27, 0x01) => "Hardware write protected",
        (0x27, 0x02) => "Logical unit software write protected",
        (0x27, 0x03) => "Associated write protect",
        (0x27, 0x04) => "Persistent write protect",
        (0x27, 0x05) => "Permanent write protect",
        (0x27, 0x06) => "Conditional write protect",
        (0x28, 0x00) => "Not ready to ready change, medium may have changed",
        (0x28, 0x01) => "Import or export element accessed",
        (0x28, 0x02) => "Format-layer may have changed",
        (0x29, 0x00) => "Power on, reset, or bus device reset occurred",
        (0x29, 0x01) => "Power on occurred",
        (0x29, 0x02) => "SCSI bus reset occurred",
        (0x29, 0x03) => "Bus device reset function occurred",
        (0x29, 0x04) => "Device internal reset",
        (0x29, 0x05) => "Transceiver mode changed to single-ended",
        (0x29, 0x06) => "Transceiver mode changed to LVD",
        (0x29, 0x07) => "I_T nexus loss occurred",
        (0x2A, 0x00) => "Parameters changed",
        (0x2A, 0x01) => "Mode parameters changed",
        (0x2A, 0x02) => "Log parameters changed",
        (0x2A, 0x03) => "Reservations preempted",
        (0x2A, 0x04) => "Reservations released",
        (0x2A, 0x05) => "Registrations preempted",
        (0x2C, 0x00) => "Command sequence error",
        (0x2C, 0x01) => "Too many windows specified",
        (0x2C, 0x02) => "Invalid combination of windows specified",
        (0x2D, 0x00) => "Overwrite error on update in place",
        (0x2F, 0x00) => "Commands cleared by another initiator",
        (0x30, 0x00) => "Incompatible medium installed",
        (0x30, 0x01) => "Cannot read medium - unknown format",
        (0x30, 0x02) => "Cannot read medium - incompatible format",
        (0x30, 0x03) => "Cleaning cartridge installed",
        (0x30, 0x04) => "Cannot write medium - unknown format",
        (0x30, 0x05) => "Cannot write medium - incompatible format",
        (0x30, 0x06) => "Cannot format medium - incompatible medium",
        (0x30, 0x07) => "Cleaning failure",
        (0x30, 0x08) => "Cannot write - application code mismatch",
        (0x30, 0x09) => "Current session not fixated for append",
        (0x30, 0x0C) => "WORM medium - overwrite attempted",
        (0x30, 0x0D) => "WORM medium - integrity check",
        (0x30, 0x10) => "Medium not formatted",
        (0x31, 0x00) => "Medium format corrupted",
        (0x31, 0x01) => "Format command failed",
        (0x32, 0x00) => "No defect spare location available",
        (0x33, 0x00) => "Tape length error",
        (0x35, 0x01) => "Unsupported enclosure function",
        (0x36, 0x00) => "Ribbon, ink, or toner failure",
        (0x37, 0x00) => "Rounded parameter",
        (0x39, 0x00) => "Saving parameters not supported",
        (0x3A, 0x00) => "Medium not present",
        (0x3A, 0x01) => "Medium not present - tray closed",
        (0x3A, 0x02) => "Medium not present - tray open",
        (0x3A, 0x03) => "Medium not present - loadable",
        (0x3A, 0x04) => "Medium not present - medium auxiliary memory accessible",
        (0x3B, 0x00) => "Sequential positioning error",
        (0x3B, 0x01) => "Tape position error at beginning-of-medium",
        (0x3B, 0x02) => "Tape position error at end-of-medium",
        (0x3B, 0x08) => "Reposition error",
        (0x3B, 0x0C) => "Position past beginning of medium",
        (0x3B, 0x0D) => "Medium destination element full",
        (0x3B, 0x0E) => "Medium source element empty",
        (0x3B, 0x0F) => "End of medium reached",
        (0x3B, 0x11) => "Medium magazine not accessible",
        (0x3B, 0x12) => "Medium magazine removed",
        (0x3B, 0x13) => "Medium magazine inserted",
        (0x3B, 0x14) => "Medium magazine locked",
        (0x3B, 0x15) => "Medium magazine unlocked",
        (0x3D, 0x00) => "Invalid bits in identify message",
        (0x3E, 0x00) => "Logical unit has not self-configured yet",
        (0x3E, 0x01) => "Logical unit failure",
        (0x3E, 0x02) => "Timeout on logical unit",
        (0x3F, 0x00) => "Target operating conditions have changed",
        (0x3F, 0x01) => "Microcode has been changed",
        (0x3F, 0x02) => "Changed operating definition",
        (0x3F, 0x03) => "Inquiry data has changed",
        (0x3F, 0x05) => "Device identifier changed",
        (0x3F, 0x0E) => "Reported LUNs data has changed",
        (0x40, 0x00) => "RAM failure (should use 40 NN)",
        (0x41, 0x00) => "Data path failure (should use 40 NN)",
        (0x42, 0x00) => "Power-on or self-test failure (should use 40 NN)",
        (0x43, 0x00) => "Message error",
        (0x44, 0x00) => "Internal target failure",
        (0x45, 0x00) => "Select or reselect failure",
        (0x46, 0x00) => "Unsuccessful soft reset",
        (0x47, 0x00) => "SCSI parity error",
        (0x47, 0x01) => "Data phase CRC error detected",
        (0x47, 0x02) => "SCSI parity error detected during ST data phase",
        (0x47, 0x03) => "Information unit iuCRC error detected",
        (0x47, 0x04) => "Asynchronous information protection error detected",
        (0x47, 0x05) => "Protocol service CRC error",
        (0x48, 0x00) => "Initiator detected error message received",
        (0x49, 0x00) => "Invalid message error",
        (0x4A, 0x00) => "Command phase error",
        (0x4B, 0x00) => "Data phase error",
        (0x4C, 0x00) => "Logical unit failed self-configuration",
        (0x4E, 0x00) => "Overlapped commands attempted",
        (0x50, 0x00) => "Write append error",
        (0x51, 0x00) => "Erase failure",
        (0x52, 0x00) => "Cartridge fault",
        (0x53, 0x00) => "Media load or eject failed",
        (0x53, 0x01) => "Unload tape failure",
        (0x53, 0x02) => "Medium removal prevented",
        (0x54, 0x00) => "SCSI to host system interface failure",
        (0x55, 0x00) => "System resource failure",
        (0x55, 0x01) => "System buffer full",
        (0x55, 0x02) => "Insufficient reservation resources",
        (0x55, 0x03) => "Insufficient resources",
        (0x55, 0x04) => "Insufficient registration resources",
        (0x57, 0x00) => "Unable to recover table-of-contents",
        (0x58, 0x00) => "Generation does not exist",
        (0x59, 0x00) => "Updated block read",
        (0x5A, 0x00) => "Operator request or state change input",
        (0x5A, 0x01) => "Operator medium removal request",
        (0x5A, 0x02) => "Operator selected write protect",
        (0x5A, 0x03) => "Operator selected write permit",
        (0x5B, 0x00) => "Log exception",
        (0x5B, 0x01) => "Threshold condition met",
        (0x5B, 0x02) => "Log counter at maximum",
        (0x5B, 0x03) => "Log list codes exhausted",
        (0x5C, 0x00) => "RPL status change",
        (0x5C, 0x01) => "Spindles synchronized",
        (0x5C, 0x02) => "Spindles not synchronized",
        (0x5D, 0x00) => "Failure prediction threshold exceeded",
        (0x5E, 0x00) => "Low power condition on",
        (0x5E, 0x01) => "Idle condition activated by timer",
        (0x5E, 0x02) => "Standby condition activated by timer",
        (0x5E, 0x03) => "Idle condition activated by command",
        (0x5E, 0x04) => "Standby condition activated by command",
        (0x65, 0x00) => "Voltage fault",
        (0x67, 0x0A) => "Set target port groups command failed",
        _ => "Unknown ASC/ASCQ",
    }
}

pub fn response_code_name(code: u8) -> &'static str {
    match code {
        0x70 => "Current errors, fixed format",
        0x71 => "Deferred errors, fixed format",
        0x72 => "Current errors, descriptor format",
        0x73 => "Deferred errors, descriptor format",
        _ => "Unknown response code",
    }
}

pub fn vpd_page_name(page: u8) -> &'static str {
    match page {
        0x00 => "Supported VPD Pages",
        0x80 => "Unit Serial Number",
        0x83 => "Device Identification",
        0x86 => "Extended INQUIRY Data",
        0x87 => "Mode Page Policy",
        0x89 => "ATA Information",
        0xB0 => "Sequential-Access Device Capabilities",
        0xB1 => "Manufacturer-assigned Serial Number",
        0xB2 => "TapeAlert Supported Flags",
        _ if page >= 0xC0 => "Vendor Specific VPD page",
        _ => "Unknown VPD page",
    }
}

pub fn mode_page_name(page: u8) -> &'static str {
    match page {
        0x00 => "Vendor Specific",
        0x01 => "Read-Write Error Recovery",
        0x02 => "Disconnect-Reconnect",
        0x0A => "Control",
        0x0F => "Data Compression",
        0x10 => "Device Configuration",
        0x11 => "Medium Partition(1)",
        0x18 => "Protocol Specific Logical Unit",
        0x19 => "Protocol Specific Port",
        0x1A => "Power Condition",
        0x1C => "Informational Exceptions Control",
        0x1D => "Element Address Assignment",
        0x1E => "Transport Geometry",
        0x1F => "Device Capabilities",
        0x3F => "All Pages",
        _ => "Unknown mode page",
    }
}

pub fn element_type_name(etype: u8) -> &'static str {
    match etype {
        0x0 => "All Types",
        0x1 => "Medium Transport",
        0x2 => "Storage",
        0x3 => "Import/Export",
        0x4 => "Data Transfer",
        _ => "Unknown",
    }
}

pub fn space_code_name(code: u8) -> &'static str {
    match code {
        0 => "Blocks",
        1 => "Filemarks",
        3 => "End-of-data",
        _ => "Unknown",
    }
}

pub fn log_page_name(page: u8) -> &'static str {
    match page {
        0x00 => "Supported Log Pages",
        0x02 => "Write Error Counters",
        0x03 => "Read Error Counters",
        0x06 => "Non-Medium Error",
        0x0C => "Sequential-Access Device",
        0x0D => "Temperature",
        0x0E => "Start-Stop Cycle Counter",
        0x10 => "Self-Test Results",
        0x11 => "DT Device Status",
        0x14 => "Device Statistics",
        0x15 => "Service Buffers Information",
        0x17 => "Volume Statistics",
        0x1B => "Data Compression",
        0x2E => "TapeAlert",
        0x31 => "Tape Capacity",
        0x3E => "Factory",
        _ if page >= 0x30 && page <= 0x3E => "Vendor-specific log page",
        _ => "Unknown log page",
    }
}

pub fn peripheral_device_type_name(pdt: u8) -> &'static str {
    match pdt {
        0x00 => "Direct access block device (disk)",
        0x01 => "Sequential-access device (tape)",
        0x02 => "Printer device",
        0x03 => "Processor device",
        0x04 => "Write-once device",
        0x05 => "CD/DVD device",
        0x07 => "Optical memory device",
        0x08 => "Medium changer device",
        0x0C => "Storage array controller device",
        0x0D => "Enclosure services device",
        0x0E => "Simplified direct-access device",
        0x11 => "Object-based storage device",
        0x12 => "Automation/drive interface",
        0x1E => "Well known logical unit",
        0x1F => "Unknown or no device type",
        _ => "Reserved",
    }
}

pub fn peripheral_qualifier_name(pq: u8) -> &'static str {
    match pq {
        0x0 => "Connected",
        0x1 => "Not connected",
        0x2 => "Reserved",
        0x3 => "Not capable of supporting a device",
        _ => "Unknown",
    }
}

pub fn density_code_name(code: u8) -> &'static str {
    match code {
        0x00 => "Default",
        0x40 => "LTO-1",
        0x42 => "LTO-2",
        0x44 => "LTO-3",
        0x46 => "LTO-4",
        0x58 => "LTO-5",
        0x5A => "LTO-6",
        0x5C => "LTO-7",
        0x5D => "LTO-7 Type M (M8)",
        0x5E => "LTO-8",
        0x60 => "LTO-9",
        _ => "Unknown density",
    }
}

/// Code set names for VPD page 83h designation descriptors.
pub fn code_set_name(cs: u8) -> &'static str {
    match cs {
        0x0 => "Reserved",
        0x1 => "Binary",
        0x2 => "ASCII",
        0x3 => "UTF-8",
        _ => "Reserved",
    }
}

/// Association names for VPD page 83h designation descriptors.
pub fn association_name(assoc: u8) -> &'static str {
    match assoc {
        0x0 => "Logical unit",
        0x1 => "Target port",
        0x2 => "Target device",
        _ => "Reserved",
    }
}

/// Designator type names for VPD page 83h.
pub fn designator_type_name(dt: u8) -> &'static str {
    match dt {
        0x0 => "Vendor specific",
        0x1 => "T10 vendor ID",
        0x2 => "EUI-64",
        0x3 => "NAA",
        0x4 => "Relative target port",
        0x5 => "Target port group",
        0x6 => "Logical unit group",
        0x7 => "MD5 logical unit",
        0x8 => "SCSI name string",
        _ => "Reserved",
    }
}

/// Protocol identifier names for VPD page 83h.
pub fn protocol_identifier_name(pi: u8) -> &'static str {
    match pi {
        0x0 => "Fibre Channel",
        0x1 => "Parallel SCSI",
        0x2 => "SSA",
        0x3 => "IEEE 1394",
        0x4 => "RDMA",
        0x5 => "iSCSI",
        0x6 => "SAS",
        0x7 => "ADT",
        0x8 => "ATA/ATAPI",
        0x9 => "UAS",
        0xA => "SOP",
        _ => "Reserved",
    }
}

/// SPC version names for standard inquiry byte 5.
pub fn version_name(version: u8) -> &'static str {
    match version {
        0x00 => "No conformance claimed",
        0x03 => "SPC",
        0x04 => "SPC-2",
        0x05 => "SPC-3",
        0x06 => "SPC-4",
        0x07 => "SPC-5",
        _ => "Unknown version",
    }
}

/// TapeAlert flag descriptions (log page 2Eh).
pub fn tape_alert_flag_name(flag: u16) -> &'static str {
    match flag {
        0x0001 => "Read warning",
        0x0002 => "Write warning",
        0x0003 => "Hard error",
        0x0004 => "Media",
        0x0005 => "Read failure",
        0x0006 => "Write failure",
        0x0007 => "Media life",
        0x0008 => "Not data grade",
        0x0009 => "Write protect",
        0x000A => "No removal",
        0x000B => "Cleaning media",
        0x000C => "Unsupported format",
        0x000D => "Recoverable snapped tape",
        0x000E => "Unrecoverable snapped tape",
        0x000F => "Memory chip in cartridge failure",
        0x0010 => "Forced eject",
        0x0011 => "Read only format",
        0x0012 => "Tape directory corrupted on load",
        0x0013 => "Nearing media life",
        0x0014 => "Clean now",
        0x0015 => "Clean periodic",
        0x0016 => "Expired cleaning media",
        0x0017 => "Invalid cleaning tape",
        0x0018 => "Retension requested",
        0x0019 => "Dual-port interface error",
        0x001A => "Cooling fan failure",
        0x001B => "Power supply failure",
        0x001C => "Power consumption",
        0x001D => "Drive maintenance",
        0x001E => "Hardware A",
        0x001F => "Hardware B",
        0x0020 => "Interface",
        0x0021 => "Eject media",
        0x0022 => "Microcode update fail",
        0x0023 => "Drive humidity",
        0x0024 => "Drive temperature",
        0x0025 => "Drive voltage",
        0x0026 => "Predictive failure",
        0x0027 => "Diagnostics required",
        0x0029 => "Loader hardware A",
        0x002A => "Loader stray tape",
        0x002B => "Loader hardware B",
        0x002E => "Loader door",
        0x002F => "Loader hardware C",
        0x0030 => "Loader magazine",
        0x0032 => "Loader predictive failure",
        0x0034 => "Lost statistics",
        0x0035 => "Tape directory invalid at unload",
        0x0036 => "Tape system area write failure",
        0x0037 => "Tape system area read failure",
        0x0038 => "No start of data",
        0x0039 => "Loading failure",
        0x003A => "Unrecoverable unload failure",
        0x003B => "Automation interface failure",
        0x003C => "Firmware failure",
        0x003D => "WORM medium - integrity check failed",
        0x003E => "WORM medium - overwrite attempted",
        _ => "Unknown TapeAlert flag",
    }
}

pub fn compression_algorithm_name(algo: u32) -> &'static str {
    match algo {
        0x00 => "No compression",
        0x03 => "IBM ALDC with 512-byte buffer",
        0x04 => "IBM ALDC with 1024-byte buffer",
        0x05 => "IBM ALDC with 2048-byte buffer",
        0x10 => "IBM IDRC",
        0x20 => "DCLZ",
        0xFF => "Vendor specific / unregistered",
        _ => "Unknown algorithm",
    }
}
