listen:
  host: "0.0.0.0"
  admin_port: 8081

store:
  path: "vtld.redb"

iscsi:
  port: 3260
  iqn: "iqn.2024-01.com.quantumvtl:vtl"

library:
  model: "Quantum Scalar i6"
  serial: "AAAABBBB0001"
  data_dir: "./data"
  drives: 4
  slots: 24
  media:
    - barcode: "ABC001L9"
      capacity_bytes: 18000000000000   # 18 TB (LTO-9)
    - barcode: "ABC002L9"
      capacity_bytes: 18000000000000
    - barcode: "ABC003L9"
      capacity_bytes: 18000000000000

users:
  - username: admin
    password: admin
